---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livego.fullname" . }}-rtmp
  labels:
    {{- include "livego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1935
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    {{- include "livego.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livego.fullname" . }}-http-flv
  labels:
    {{- include "livego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7001
      targetPort: http-flv
      protocol: TCP
      name: http-flv
  selector:
    {{- include "livego.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livego.fullname" . }}-http-fls
  labels:
    {{- include "livego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 7002
      targetPort: http-hls
      protocol: TCP
      name: http-hls
  selector:
    {{- include "livego.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livego.fullname" . }}-http-api
  labels:
    {{- include "livego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8090
      targetPort: http-api
      protocol: TCP
      name: http-api
  selector:
    {{- include "livego.selectorLabels" . | nindent 4 }}
