apiVersion: v1
kind: Service
metadata:
  name: {{ include "livego.fullname" . }}-rtmp
  labels:
    {{- include "livego.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 1935
      targetPort: rtmp
      protocol: TCP
      name: rtmp
  selector:
    {{- include "livego.selectorLabels" . | nindent 4 }}
